"use client"

import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import {
  Video, Users, MapPin, Sparkles, Plus, ChevronRight,
  CheckCircle2, Circle, Copy, Check, FileText, Mic,
  Clock, Calendar, ArrowRight, MessageSquare,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

const platformConfig = {
  zoom: { label: "Zoom", icon: Video, color: "text-blue-500", bg: "bg-blue-50" },
  teams: { label: "Teams", icon: Video, color: "text-indigo-500", bg: "bg-indigo-50" },
  meet: { label: "Google Meet", icon: Video, color: "text-emerald-500", bg: "bg-emerald-50" },
  in_person: { label: "In Person", icon: MapPin, color: "text-amber-500", bg: "bg-amber-50" },
}

const mockMeetings = [
  {
    id: "m1",
    title: "Sprint Planning — dxPOS v3",
    date: "2026-07-02",
    startTime: "10:00",
    endTime: "11:00",
    attendees: ["Nasim", "Ahmed", "Sara", "Client"],
    platform: "zoom" as const,
    status: "upcoming",
    notes: "",
    actionItems: [] as { id: string; title: string; assignee: string; completed: boolean }[],
    summary: "",
  },
  {
    id: "m2",
    title: "Nexus AI Architecture Review",
    date: "2026-07-01",
    startTime: "15:30",
    endTime: "16:00",
    attendees: ["Nasim"],
    platform: "in_person" as const,
    status: "today",
    notes: "Review agent architecture and decide on vector DB strategy.",
    actionItems: [] as { id: string; title: string; assignee: string; completed: boolean }[],
    summary: "",
  },
  {
    id: "m3",
    title: "Client Demo — dxPOS Mobile",
    date: "2026-07-01",
    startTime: "14:00",
    endTime: "15:00",
    attendees: ["Nasim", "Ahmed", "Client"],
    platform: "meet" as const,
    status: "today",
    notes: "",
    actionItems: [] as { id: string; title: string; assignee: string; completed: boolean }[],
    summary: "",
  },
  {
    id: "m4",
    title: "Accessibility Audit Walkthrough",
    date: "2026-06-30",
    startTime: "11:00",
    endTime: "11:30",
    attendees: ["Nasim", "Sara"],
    platform: "zoom" as const,
    status: "past",
    notes: "Went through WCAG 2.1 issues in dxPOS v3. Fixed 4 critical issues, 8 warnings remaining.",
    actionItems: [
      { id: "a1", title: "Fix contrast ratio on primary buttons", assignee: "Nasim", completed: true },
      { id: "a2", title: "Add ARIA labels to navigation items", assignee: "Ahmed", completed: false },
      { id: "a3", title: "Review keyboard navigation flow", assignee: "Sara", completed: false },
    ],
    summary: "Reviewed WCAG 2.1 compliance for dxPOS v3. Critical issues prioritized for sprint 8.",
  },
  {
    id: "m5",
    title: "HR Module — Client Requirements",
    date: "2026-06-27",
    startTime: "14:00",
    endTime: "15:00",
    attendees: ["Nasim", "Ahmed", "Client"],
    platform: "meet" as const,
    status: "past",
    notes: "Client wants a redesigned leave management calendar and employee dashboard.",
    actionItems: [
      { id: "a4", title: "Create leave calendar wireframes", assignee: "Nasim", completed: true },
      { id: "a5", title: "Write requirements document", assignee: "Ahmed", completed: true },
      { id: "a6", title: "Share Figma link with client", assignee: "Nasim", completed: false },
    ],
    summary: "Gathered requirements for HR module redesign. Leave management and employee dashboard are top priorities.",
  },
]

const STANDUP_TEMPLATE = `**Yesterday:**
- Completed WCAG 2.1 accessibility audit walkthrough for dxPOS v3
- Designed leave management calendar component (HR Module UI)
- Set up initial Nexus AI project scaffold

**Today:**
- Client demo — dxPOS Mobile at 2:00 PM
- Continue checkout flow hi-fi screens in Figma
- Architecture review at 3:30 PM

**Blockers:**
- None currently. Waiting on client feedback for HR module color palette.

---
*Generated by Nexus AI · ${new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}*`

const AI_SUMMARY = `## Meeting Summary: Accessibility Audit Walkthrough

**Date:** June 30, 2026 · 11:00 AM – 11:30 AM
**Attendees:** Nasim, Sara
**Platform:** Zoom

### Key Discussion Points
- Reviewed all WCAG 2.1 failures in dxPOS v3 checkout flow
- Contrast ratio on CTA buttons is below 4.5:1 threshold
- Navigation items missing ARIA labels
- Keyboard tab order needs fixing in the cart modal

### Decisions Made
- Fix all Level A violations before July 5 release
- Level AA violations tracked as tech debt for next sprint

### Action Items
1. ✅ Fix contrast ratio on primary buttons — Nasim (Done)
2. ⬜ Add ARIA labels to navigation items — Ahmed
3. ⬜ Review keyboard navigation flow — Sara

### AI Insights
The team is on track. 4 of 12 issues resolved. Estimated 2 more sessions to close all critical findings.`

const container = { hidden: { opacity: 0 }, show: { opacity: 1, transition: { staggerChildren: 0.06 } } }
const item = { hidden: { opacity: 0, y: 12 }, show: { opacity: 1, y: 0 } }

export function Meetings() {
  const [activeTab, setActiveTab] = useState<"all" | "today" | "upcoming" | "past">("all")
  const [selectedMeeting, setSelectedMeeting] = useState<string | null>("m4")
  const [showStandup, setShowStandup] = useState(false)
  const [showSummary, setShowSummary] = useState(false)
  const [copied, setCopied] = useState(false)
  const [generatingSummary, setGeneratingSummary] = useState(false)
  const [generatedSummary, setGeneratedSummary] = useState(false)

  const filtered = mockMeetings.filter((m) => activeTab === "all" || m.status === activeTab)
  const selected = mockMeetings.find((m) => m.id === selectedMeeting)

  const handleCopy = () => {
    navigator.clipboard.writeText(STANDUP_TEMPLATE).catch(() => {})
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleGenerateSummary = async () => {
    setGeneratingSummary(true)
    await new Promise((r) => setTimeout(r, 1600))
    setGeneratingSummary(false)
    setGeneratedSummary(true)
    setShowSummary(true)
  }

  return (
    <div className="flex h-full overflow-hidden">
      {/* Left: Meeting List */}
      <motion.div
        variants={container}
        initial="hidden"
        animate="show"
        className="flex w-80 shrink-0 flex-col border-r border-neutral-100 bg-white overflow-hidden"
      >
        {/* Header */}
        <motion.div variants={item} className="border-b border-neutral-100 p-4">
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-sm font-semibold text-neutral-900">Meetings</h2>
            <Button size="sm" className="gap-1.5 h-7 text-xs">
              <Plus className="h-3 w-3" /> New
            </Button>
          </div>
          {/* Tabs */}
          <div className="flex gap-1 rounded-lg bg-neutral-100 p-1">
            {(["all", "today", "upcoming", "past"] as const).map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`flex-1 rounded-md py-1 text-[10px] font-medium capitalize transition-colors ${
                  activeTab === tab ? "bg-white shadow-sm text-neutral-800" : "text-neutral-500"
                }`}
              >
                {tab}
              </button>
            ))}
          </div>
        </motion.div>

        {/* Quick Actions */}
        <motion.div variants={item} className="border-b border-neutral-100 p-3 space-y-1.5">
          <button
            onClick={() => setShowStandup(!showStandup)}
            className="flex w-full items-center gap-2.5 rounded-lg bg-indigo-50 px-3 py-2.5 text-left hover:bg-indigo-100 transition-colors"
          >
            <Sparkles className="h-3.5 w-3.5 text-indigo-500 shrink-0" />
            <div>
              <p className="text-xs font-medium text-indigo-700">Generate Stand-up</p>
              <p className="text-[10px] text-indigo-500">AI-generated daily update</p>
            </div>
            <ChevronRight className={`ml-auto h-3.5 w-3.5 text-indigo-400 transition-transform ${showStandup ? "rotate-90" : ""}`} />
          </button>
        </motion.div>

        {/* Stand-up panel */}
        <AnimatePresence>
          {showStandup && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className="overflow-hidden border-b border-neutral-100"
            >
              <div className="p-3">
                <div className="rounded-lg bg-neutral-50 p-3">
                  <pre className="text-[10px] text-neutral-600 whitespace-pre-wrap leading-relaxed font-mono">
                    {STANDUP_TEMPLATE}
                  </pre>
                </div>
                <div className="mt-2 flex gap-2">
                  <button
                    onClick={handleCopy}
                    className="flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-neutral-200 py-1.5 text-[10px] font-medium text-neutral-600 hover:bg-neutral-50 transition-colors"
                  >
                    {copied ? <Check className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3" />}
                    {copied ? "Copied!" : "Copy"}
                  </button>
                  <button className="flex flex-1 items-center justify-center gap-1.5 rounded-lg bg-indigo-600 py-1.5 text-[10px] font-semibold text-white hover:bg-indigo-700 transition-colors">
                    <MessageSquare className="h-3 w-3" /> Slack
                  </button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Meeting list */}
        <div className="flex-1 overflow-y-auto p-2 space-y-1">
          {filtered.map((meeting) => {
            const platform = platformConfig[meeting.platform]
            const PIcon = platform.icon
            const isSelected = selectedMeeting === meeting.id
            return (
              <button
                key={meeting.id}
                onClick={() => setSelectedMeeting(meeting.id)}
                className={`group flex w-full items-start gap-3 rounded-xl px-3 py-3 text-left transition-all ${
                  isSelected
                    ? "bg-indigo-50 border border-indigo-100"
                    : "hover:bg-neutral-50 border border-transparent"
                }`}
              >
                <div className={`mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg ${platform.bg}`}>
                  <PIcon className={`h-3.5 w-3.5 ${platform.color}`} />
                </div>
                <div className="flex-1 min-w-0">
                  <p className={`text-xs font-medium truncate ${isSelected ? "text-indigo-700" : "text-neutral-800"}`}>
                    {meeting.title}
                  </p>
                  <p className="text-[10px] text-neutral-400 mt-0.5">
                    {meeting.date === "2026-07-01" ? "Today" : new Date(meeting.date).toLocaleDateString("en-US", { month: "short", day: "numeric" })}
                    {" · "}{meeting.startTime} – {meeting.endTime}
                  </p>
                  {meeting.actionItems.length > 0 && (
                    <p className="text-[10px] text-neutral-400 mt-0.5">
                      {meeting.actionItems.filter((a) => a.completed).length}/{meeting.actionItems.length} action items
                    </p>
                  )}
                </div>
                {meeting.status === "today" && (
                  <span className="shrink-0 rounded-full bg-red-100 px-1.5 py-0.5 text-[9px] font-semibold text-red-600">Today</span>
                )}
              </button>
            )
          })}
        </div>
      </motion.div>

      {/* Right: Meeting Detail */}
      <div className="flex-1 overflow-y-auto">
        {selected ? (
          <motion.div
            key={selected.id}
            initial={{ opacity: 0, x: 10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.2 }}
            className="p-6 max-w-3xl"
          >
            {/* Meeting header */}
            <div className="mb-6">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    {selected.status === "today" && (
                      <Badge className="bg-red-100 text-red-600 border-0 text-[10px]">Today</Badge>
                    )}
                    {selected.status === "upcoming" && (
                      <Badge className="bg-blue-100 text-blue-600 border-0 text-[10px]">Upcoming</Badge>
                    )}
                  </div>
                  <h2 className="text-xl font-semibold text-neutral-900">{selected.title}</h2>
                  <div className="flex items-center gap-4 mt-2 text-sm text-neutral-500">
                    <span className="flex items-center gap-1.5">
                      <Calendar className="h-3.5 w-3.5" />
                      {new Date(selected.date).toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}
                    </span>
                    <span className="flex items-center gap-1.5">
                      <Clock className="h-3.5 w-3.5" />
                      {selected.startTime} – {selected.endTime}
                    </span>
                  </div>
                </div>
                {selected.status === "past" && (
                  <div className="flex gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      className="gap-1.5 text-xs"
                      onClick={handleGenerateSummary}
                      disabled={generatingSummary}
                    >
                      {generatingSummary ? (
                        <>
                          <div className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-indigo-300 border-t-indigo-600" />
                          Summarizing…
                        </>
                      ) : (
                        <>
                          <Sparkles className="h-3.5 w-3.5 text-indigo-500" />
                          AI Summary
                        </>
                      )}
                    </Button>
                  </div>
                )}
              </div>
            </div>

            {/* Attendees + Platform */}
            <div className="grid grid-cols-2 gap-4 mb-6">
              <Card>
                <CardContent className="p-4">
                  <p className="text-xs text-neutral-400 mb-2 font-medium uppercase tracking-wider">Platform</p>
                  <div className="flex items-center gap-2">
                    <div className={`flex h-8 w-8 items-center justify-center rounded-lg ${platformConfig[selected.platform].bg}`}>
                      <Video className={`h-4 w-4 ${platformConfig[selected.platform].color}`} />
                    </div>
                    <span className="text-sm font-medium text-neutral-800">{platformConfig[selected.platform].label}</span>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <p className="text-xs text-neutral-400 mb-2 font-medium uppercase tracking-wider">Attendees</p>
                  <div className="flex items-center gap-1.5">
                    <div className="flex -space-x-1.5">
                      {selected.attendees.slice(0, 4).map((a, i) => (
                        <div
                          key={a}
                          className="flex h-7 w-7 items-center justify-center rounded-full border-2 border-white bg-indigo-100 text-[10px] font-bold text-indigo-700"
                          style={{ zIndex: 10 - i }}
                        >
                          {a[0]}
                        </div>
                      ))}
                    </div>
                    <span className="text-xs text-neutral-500 ml-1">{selected.attendees.join(", ")}</span>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* AI Summary */}
            <AnimatePresence>
              {(showSummary || selected.summary) && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: "auto" }}
                  exit={{ opacity: 0, height: 0 }}
                  className="mb-5"
                >
                  <Card className="border-indigo-100 bg-gradient-to-br from-indigo-50/60 to-white">
                    <CardHeader className="pb-2">
                      <div className="flex items-center gap-2">
                        <Sparkles className="h-4 w-4 text-indigo-500" />
                        <CardTitle className="text-indigo-900 text-sm">AI Summary</CardTitle>
                      </div>
                    </CardHeader>
                    <CardContent>
                      <div className="prose prose-sm max-w-none text-neutral-700">
                        {AI_SUMMARY.split("\n").map((line, i) => (
                          <p key={i} className={`${line.startsWith("##") ? "text-sm font-semibold text-neutral-800 mt-0" : line.startsWith("###") ? "text-xs font-semibold text-neutral-700 mt-2 mb-0.5" : "text-xs leading-relaxed text-neutral-600"}`}>
                            {line.replace(/^##+ /, "")}
                          </p>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Notes */}
            {selected.notes && (
              <Card className="mb-5">
                <CardHeader className="pb-2">
                  <div className="flex items-center gap-2">
                    <FileText className="h-4 w-4 text-neutral-400" />
                    <CardTitle>Notes</CardTitle>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-neutral-600 leading-relaxed">{selected.notes}</p>
                </CardContent>
              </Card>
            )}

            {/* Action Items */}
            {selected.actionItems.length > 0 && (
              <Card className="mb-5">
                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <CheckCircle2 className="h-4 w-4 text-neutral-400" />
                      <CardTitle>Action Items</CardTitle>
                    </div>
                    <span className="text-xs text-neutral-400">
                      {selected.actionItems.filter((a) => a.completed).length}/{selected.actionItems.length} done
                    </span>
                  </div>
                </CardHeader>
                <CardContent className="space-y-2">
                  {selected.actionItems.map((action) => (
                    <div key={action.id} className="flex items-center gap-3 rounded-lg px-3 py-2.5 hover:bg-neutral-50 transition-colors">
                      {action.completed ? (
                        <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0" />
                      ) : (
                        <Circle className="h-4 w-4 text-neutral-300 shrink-0" />
                      )}
                      <p className={`flex-1 text-sm ${action.completed ? "line-through text-neutral-400" : "text-neutral-800"}`}>
                        {action.title}
                      </p>
                      <div className="flex h-5 w-5 items-center justify-center rounded-full bg-neutral-100 text-[10px] font-semibold text-neutral-600">
                        {action.assignee[0]}
                      </div>
                      <span className="text-xs text-neutral-400">{action.assignee}</span>
                    </div>
                  ))}
                </CardContent>
              </Card>
            )}

            {/* Upcoming meeting prompt */}
            {selected.status !== "past" && (
              <Card className="border-dashed border-neutral-200 bg-neutral-50/50">
                <CardContent className="p-5 flex flex-col items-center gap-3 text-center">
                  <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neutral-100">
                    <Mic className="h-5 w-5 text-neutral-400" />
                  </div>
                  <div>
                    <p className="text-sm font-medium text-neutral-700">Meeting not yet started</p>
                    <p className="text-xs text-neutral-400 mt-0.5">After the meeting, Nexus AI will generate a summary, extract action items, and send follow-ups.</p>
                  </div>
                </CardContent>
              </Card>
            )}
          </motion.div>
        ) : (
          <div className="flex h-full items-center justify-center">
            <div className="text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-neutral-100 mx-auto mb-3">
                <Users className="h-6 w-6 text-neutral-400" />
              </div>
              <p className="text-sm font-medium text-neutral-600">Select a meeting</p>
              <p className="text-xs text-neutral-400 mt-1">View details, notes, and action items</p>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
